{
 "title": "Hardware Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serversAll",
    "query": {
     "query": "label_values(up{job=\"hardwareMonitoring\"},instance)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(up{job=\"hardwareMonitoring\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node $serversAll",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "serversAll",
   "targets": [
    {
     "expr": "sum((1-up{job=\"hardwareMonitoring\",instance=\"$serversAll\"})*100+(scalar(100*(1-avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$serversAll\",job=\"hardwareMonitoring\"}[5m]))))>bool 80)+(scalar(avg(1-(node_memory_free_bytes{job=\"hardwareMonitoring\",instance=\"$serversAll\"}+node_memory_purgeable_bytes{job=\"hardwareMonitoring\",instance=\"$serversAll\"})/node_memory_total_bytes{job=\"hardwareMonitoring\",instance=\"$serversAll\"})*100)>bool 80)+(scalar((sum(node_filesystem_size_bytes{job=\"hardwareMonitoring\",instance=\"$serversAll\"})-sum(node_filesystem_free_bytes{job=\"hardwareMonitoring\",instance=\"$serversAll\"}))/sum(node_filesystem_size_bytes{job=\"hardwareMonitoring\",instance=\"$serversAll\"})*100)>bool 80))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100*(1-avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Node\",job=\"hardwareMonitoring\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(1-(node_memory_free_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"}+node_memory_purgeable_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})/node_memory_total_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})-sum(node_filesystem_free_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"}))/sum(node_filesystem_size_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(1-avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Node\",job=\"hardwareMonitoring\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(1-(node_memory_free_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"}+node_memory_purgeable_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})/node_memory_total_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})-sum(node_filesystem_free_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"}))/sum(node_filesystem_size_bytes{job=\"hardwareMonitoring\",instance=\"$Node\"})*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}