{
 "title": "Log monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Job logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spark-master\"} |= `INFO` |= `Job` |= `took`"
    }
   ]
  },
  {
   "title": "Warning logs spark-master",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spark-master\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "Warning logs spark-worker",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spark-worker\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "Error logs spark-master",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spark-master\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Error logs spark-worker",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spark-worker\"} |= `Caused by` or `ERROR`"
    }
   ]
  }
 ]
}